apiVersion: argoproj.io/v1alpha1
kind: Application
metadata: 
  labels:
    app: appofapps
  name: appofapps
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/hazardsoft/ArgoCD.git
    path: ./Argo-CD-for-the-Absolute-Beginners-main/Section13_Declarative_Demo/apps
  destination:
    server: https://kubernetes.default.svc